language: d

os:
    - linux
    - osx

sudo: false

d:
    - dmd
    - gdc
    - ldc2
    
install:
    - dub fetch doveralls
    - dub build doveralls

script:
    - git submodule update --init --recursive
    - dub test --arch=x86 --build=unittest-cov
    - dub test --arch=x86_64 --build=unittest
    - dub test --arch=x86 --build=optimized-unittest
    - dub test --arch=x86_64 --build=optimized-unittest
    - dub test --arch=x86 --build=release-unittest
    - dub test --arch=x86_64 --build=release-unittest
    - dub run doveralls